// components/barber/BarberCardModal.tsx
// Barber Card generator — renders a shareable card and provides share actions

import { useRef } from 'react'
import {
    View,
    Text,
    StyleSheet,
    Pressable,
    Modal,
    Share,
    Linking,
    Alert,
    ScrollView,
} from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import * as Haptics from 'expo-haptics'
import { Colors } from '@/constants/colors'
import { Typography } from '@/constants/typography'
import { Spacing, BorderRadius } from '@/constants/spacing'
import { type Hairstyle } from '@/constants/hairstyles'

interface BarberCardModalProps {
    hairstyle: Hairstyle
    onClose: () => void
}

export function BarberCardModal({ hairstyle, onClose }: BarberCardModalProps) {
    async function shareViaWhatsApp() {
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)
        const text = `🪒 *${hairstyle.name}*\n\n${hairstyle.barberScript}\n\n🔢 *Guard Numbers:*\n${Object.entries(hairstyle.guardNumbers)
            .map(([k, v]) => `• ${k.replace(/_/g, ' ')}: ${v}`)
            .join('\n')}\n\n_Generated by GroomAI_`
        const msg = encodeURIComponent(text)
        const url = `whatsapp://send?text=${msg}`
        const supported = await Linking.canOpenURL(url)
        if (supported) {
            Linking.openURL(url)
        } else {
            Alert.alert('WhatsApp not installed', 'Would you like to share via another app?', [
                { text: 'Cancel', style: 'cancel' },
                { text: 'Share', onPress: () => shareGeneric() },
            ])
        }
    }

    async function shareGeneric() {
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)
        const guardText = Object.entries(hairstyle.guardNumbers)
            .map(([k, v]) => `• ${k.replace(/_/g, ' ')}: ${v}`)
            .join('\n')

        Share.share({
            title: `${hairstyle.name} — Barber Brief`,
            message: `✂️ ${hairstyle.name}\n\n💬 What to say:\n${hairstyle.barberScript}\n\n🔢 Guard Numbers:\n${guardText}\n\n🗓 Maintenance: ${hairstyle.maintenanceFrequency ?? 'Ask barber'}\n\n— GroomAI | groomai.app`,
        })
    }

    return (
        <Modal
            visible
            animationType="slide"
            presentationStyle="pageSheet"
            onRequestClose={onClose}
        >
            <View style={styles.modalContainer}>
                {/* Modal Header */}
                <View style={styles.modalHeader}>
                    <Text style={styles.modalTitle}>Barber Brief Card</Text>
                    <Pressable style={styles.closeBtn} onPress={onClose}>
                        <Ionicons name="close" size={22} color={Colors.text.primary} />
                    </Pressable>
                </View>

                <ScrollView contentContainerStyle={styles.modalScroll} showsVerticalScrollIndicator={false}>
                    {/* The BarberCard — designed to look great when screenshotted */}
                    <View style={styles.card}>
                        {/* Header */}
                        <View style={styles.cardHeader}>
                            <View style={styles.cardBrand}>
                                <Ionicons name="cut" size={16} color={Colors.gold.primary} />
                                <Text style={styles.cardBrandText}>GroomAI</Text>
                            </View>
                            <Text style={styles.cardSubtitle}>Barber Brief</Text>
                        </View>

                        {/* Style name */}
                        <Text style={styles.cardStyleName}>{hairstyle.name}</Text>
                        {hairstyle.technicalName && (
                            <Text style={styles.cardTechnicalName}>{hairstyle.technicalName}</Text>
                        )}

                        {/* Face shapes */}
                        <View style={styles.cardFaceShapes}>
                            {hairstyle.faceShapes.map((f) => (
                                <View key={f} style={styles.cardFaceTag}>
                                    <Text style={styles.cardFaceTagText}>{f.charAt(0).toUpperCase() + f.slice(1)}</Text>
                                </View>
                            ))}
                        </View>

                        <View style={styles.cardDivider} />

                        {/* Barber Script */}
                        <Text style={styles.cardSectionLabel}>💬 What to say:</Text>
                        <Text style={styles.cardScript}>{hairstyle.barberScript}</Text>

                        <View style={styles.cardDivider} />

                        {/* Guard Numbers */}
                        {Object.keys(hairstyle.guardNumbers).length > 0 && (
                            <>
                                <Text style={styles.cardSectionLabel}>🔢 Guard Numbers:</Text>
                                {Object.entries(hairstyle.guardNumbers).map(([key, value]) => (
                                    <View key={key} style={styles.cardGuardRow}>
                                        <Text style={styles.cardGuardKey}>
                                            {key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}
                                        </Text>
                                        <Text style={styles.cardGuardValue}>{value}</Text>
                                    </View>
                                ))}
                            </>
                        )}

                        {hairstyle.maintenanceFrequency && (
                            <>
                                <View style={styles.cardDivider} />
                                <Text style={styles.cardSectionLabel}>🗓 Maintenance:</Text>
                                <Text style={styles.cardMaintenanceText}>{hairstyle.maintenanceFrequency}</Text>
                            </>
                        )}

                        {/* Footer watermark */}
                        <View style={styles.cardFooter}>
                            <Text style={styles.cardFooterText}>Generated by GroomAI · groomai.app</Text>
                        </View>
                    </View>

                    {/* Hint */}
                    <Text style={styles.screenshotHint}>
                        📱 Screenshot this card or share it directly with your barber
                    </Text>

                    {/* Share Actions */}
                    <View style={styles.shareActions}>
                        <Pressable style={styles.whatsappBtn} onPress={shareViaWhatsApp}>
                            <Ionicons name="logo-whatsapp" size={20} color="#fff" />
                            <Text style={styles.whatsappBtnText}>Send via WhatsApp</Text>
                        </Pressable>

                        <Pressable style={styles.shareBtn} onPress={shareGeneric}>
                            <Ionicons name="share-social-outline" size={20} color={Colors.text.primary} />
                            <Text style={styles.shareBtnText}>Share</Text>
                        </Pressable>
                    </View>
                </ScrollView>
            </View>
        </Modal>
    )
}

const styles = StyleSheet.create({
    modalContainer: { flex: 1, backgroundColor: Colors.bg.primary },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: Spacing.lg,
        borderBottomWidth: 1,
        borderBottomColor: Colors.bg.tertiary,
    },
    modalTitle: { ...Typography.h2, color: Colors.text.primary },
    closeBtn: {
        width: 36, height: 36, borderRadius: 18,
        backgroundColor: Colors.bg.secondary,
        justifyContent: 'center', alignItems: 'center',
    },
    modalScroll: { padding: Spacing.lg, paddingBottom: 60 },

    // The card itself
    card: {
        backgroundColor: Colors.bg.secondary,
        borderRadius: BorderRadius.xl ?? 24,
        padding: Spacing.lg,
        borderWidth: 1,
        borderColor: Colors.gold.muted,
        gap: Spacing.sm,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Spacing.xs,
    },
    cardBrand: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    cardBrandText: { ...Typography.bodyMedium, color: Colors.gold.primary, fontWeight: '700' },
    cardSubtitle: { ...Typography.caption, color: Colors.text.tertiary, letterSpacing: 1.5 },
    cardStyleName: { ...Typography.h2, color: Colors.text.primary },
    cardTechnicalName: { ...Typography.small, color: Colors.text.tertiary, fontStyle: 'italic' },
    cardFaceShapes: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
    cardFaceTag: {
        backgroundColor: Colors.overlay.gold,
        paddingHorizontal: 8, paddingVertical: 2,
        borderRadius: BorderRadius.full,
        borderWidth: 1, borderColor: Colors.gold.muted,
    },
    cardFaceTagText: { ...Typography.caption, color: Colors.gold.primary },
    cardDivider: { height: 1, backgroundColor: Colors.bg.tertiary, marginVertical: Spacing.xs },
    cardSectionLabel: { ...Typography.label, color: Colors.text.secondary },
    cardScript: {
        ...Typography.body, color: Colors.text.primary,
        lineHeight: 24, fontStyle: 'italic',
    },
    cardGuardRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 3,
    },
    cardGuardKey: { ...Typography.small, color: Colors.text.secondary },
    cardGuardValue: { ...Typography.small, color: Colors.text.primary, fontWeight: '700' },
    cardMaintenanceText: { ...Typography.body, color: Colors.text.secondary },
    cardFooter: {
        borderTopWidth: 1,
        borderTopColor: Colors.bg.tertiary,
        paddingTop: Spacing.sm,
        marginTop: Spacing.xs,
        alignItems: 'center',
    },
    cardFooterText: { ...Typography.caption, color: Colors.text.tertiary },

    screenshotHint: {
        ...Typography.small,
        color: Colors.text.tertiary,
        textAlign: 'center',
        marginTop: Spacing.md,
        marginBottom: Spacing.lg,
        lineHeight: 18,
    },

    shareActions: { gap: Spacing.sm },
    whatsappBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: Spacing.sm,
        backgroundColor: '#25D366',
        borderRadius: BorderRadius.md,
        paddingVertical: 14,
    },
    whatsappBtnText: { ...Typography.bodyMedium, color: '#fff', fontWeight: '700' },
    shareBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: Spacing.sm,
        borderRadius: BorderRadius.md,
        paddingVertical: 14,
        borderWidth: 1,
        borderColor: Colors.bg.tertiary,
        backgroundColor: Colors.bg.secondary,
    },
    shareBtnText: { ...Typography.bodyMedium, color: Colors.text.primary },
})
