// constants/hairstyles.ts
// Complete hairstyle library for the Barber Translator feature
// 50+ entries covering short, medium, long, beard, and combo styles

export type FaceShape = 'oval' | 'square' | 'round' | 'oblong' | 'diamond' | 'heart' | 'triangle'
export type HairType = 'straight' | 'wavy' | 'curly' | 'coily'
export type HairstyleCategory = 'short' | 'medium' | 'long' | 'beard' | 'combo'

export interface GuardNumbers {
    [key: string]: string
}

export interface Hairstyle {
    id: string
    name: string
    slug: string
    category: HairstyleCategory
    faceShapes: FaceShape[]
    hairTypes: HairType[]
    description: string
    barberScript: string
    technicalName?: string
    guardNumbers: GuardNumbers
    stylingInstructions?: string
    maintenanceFrequency?: string
    thumbnailUrl?: string
    frontViewUrl?: string
    sideViewUrl?: string
    backViewUrl?: string
    deepArEffectId?: string
    isPremium: boolean
    isTrending: boolean
}

export const HAIRSTYLES: Hairstyle[] = [
    // ── SHORT STYLES ──────────────────────────────────────────────────────────

    {
        id: '1',
        name: 'Mid Fade + Textured Top',
        slug: 'mid-fade-textured-top',
        category: 'short',
        faceShapes: ['oval', 'square', 'oblong'],
        hairTypes: ['straight', 'wavy'],
        description: 'Clean fade with natural texture on top. Low maintenance, high impact.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I'd like a mid fade on the sides and back — starting about halfway up the head. Leave about 2 to 2.5 inches on top and use scissors, not clippers. I want texture on top so I can style it messy or pushed back. Please line up the front and around the ears. And take a little off the length but keep the shape."`,
        technicalName: 'Mid Skin Fade with Scissor-Cut Textured Top',
        guardNumbers: { sides_bottom: '0 (skin)', sides_mid: '1.5', sides_blend: '3', top: 'Scissor cut, 2–2.5 inches' },
        stylingInstructions: 'Apply a small amount of matte clay or pomade to slightly damp hair. Work in with fingers, then style upward or to the side for texture.',
        maintenanceFrequency: 'Every 3–4 weeks to maintain the fade',
    },
    {
        id: '2',
        name: 'Classic Taper',
        slug: 'classic-taper',
        category: 'short',
        faceShapes: ['round', 'oval', 'square', 'heart'],
        hairTypes: ['straight', 'wavy', 'curly'],
        description: 'Timeless taper that suits all occasions. Clean, professional look.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I'd like a classic taper — not a fade. Keep the hair on top around 1.5 to 2 inches, comb it to the side. I want it clean around the ears and the neckline blocked straight. Use a 2 on the sides, tapered down to a 1 near the bottom."`,
        technicalName: 'Side-Part Taper',
        guardNumbers: { sides: '2', taper_bottom: '1', top: 'Scissor, 1.5–2 inches' },
        maintenanceFrequency: 'Every 4–5 weeks',
    },
    {
        id: '3',
        name: 'Buzz Cut',
        slug: 'buzz-cut',
        category: 'short',
        faceShapes: ['oval', 'square', 'diamond'],
        hairTypes: ['straight', 'wavy', 'curly', 'coily'],
        description: 'Military-clean, zero maintenance. Looks sharp on strong face shapes.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I'd like an all-over buzz cut with a number 3 guard all around. Keep it even, line up the hairline and neckline cleanly."`,
        technicalName: 'Induction Cut / Uniform Buzz',
        guardNumbers: { all_over: '3' },
        maintenanceFrequency: 'Every 2–3 weeks',
    },
    {
        id: '4',
        name: 'French Crop with Low Fade',
        slug: 'french-crop-low-fade',
        category: 'short',
        faceShapes: ['oval', 'square', 'oblong'],
        hairTypes: ['straight', 'wavy'],
        description: 'European-inspired crop with a sharp fringe and precision fade.',
        isPremium: true,
        isTrending: true,
        barberScript: `"I'd like a French crop. Short and textured on top, about an inch, with a blunt or slightly textured fringe sitting on or just above my forehead. Low fade on the sides — starting about 2 inches from the bottom, blending from a 0 up to a 2. Line the front fringe straight across."`,
        technicalName: 'French Crop with Low Skin Fade',
        guardNumbers: { sides_bottom: '0', sides_blend: '2', top: 'Scissor, 1 inch' },
        stylingInstructions: 'Use a light styling cream or sea salt spray. Push fringe forward and let it dry naturally.',
        maintenanceFrequency: 'Every 3–4 weeks',
    },
    {
        id: '5',
        name: 'High Fade + Hard Part',
        slug: 'high-fade-hard-part',
        category: 'short',
        faceShapes: ['oval', 'square', 'diamond'],
        hairTypes: ['straight', 'wavy'],
        description: 'Aggressive high fade with a razor-sharp hard part line.',
        isPremium: true,
        isTrending: true,
        barberScript: `"I'd like a high skin fade on the sides and back — going almost all the way up, about 2 inches from the top. Leave 2 inches on top. I also want a hard part shaved in on my natural part line, left side. Line me up clean on the hairline and neck."`,
        technicalName: 'High Skin Fade with Razor Part',
        guardNumbers: { sides: '0 (skin to high)', top: 'Scissor, 2 inches' },
        stylingInstructions: 'Apply pomade or wax, comb to the side over the hard part for a clean, polished look.',
        maintenanceFrequency: 'Every 2–3 weeks',
    },
    {
        id: '6',
        name: 'Skin Fade + Fringe',
        slug: 'skin-fade-fringe',
        category: 'short',
        faceShapes: ['oblong', 'oval', 'heart'],
        hairTypes: ['straight', 'wavy'],
        description: 'Clean skin fade that contrasts with a forward-sweeping fringe.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I'd like a skin fade on the sides, starting from skin at the bottom and blending up. Leave about 2 inches on top, and I want the fringe swept forward or slightly to one side. Keep the fringe about eyebrow length. Clean up the neckline straight."`,
        guardNumbers: { sides: '0 to 2 blend', top: 'Scissor, 2 inches' },
        maintenanceFrequency: 'Every 3 weeks',
    },
    {
        id: '7',
        name: 'Low Fade + Slick Back',
        slug: 'low-fade-slick-back',
        category: 'short',
        faceShapes: ['oval', 'square', 'oblong'],
        hairTypes: ['straight', 'wavy'],
        description: 'Clean professional look. Works in the boardroom and after hours.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I'd like a low fade on the sides — just cleaning up the edges about an inch or two. Leave 3 inches on top so I can slick it back. Use scissors on top only. Round the neckline."`,
        guardNumbers: { sides_bottom: '1', sides_blend: '3', top: 'Scissor, 3 inches' },
        stylingInstructions: 'Apply medium-hold pomade to damp hair. Comb all the way back using a fine-toothed comb. Blow-dry for lift.',
        maintenanceFrequency: 'Every 4–5 weeks',
    },
    {
        id: '8',
        name: 'Taper Fade + Waves',
        slug: 'taper-fade-waves',
        category: 'short',
        faceShapes: ['oval', 'round', 'square'],
        hairTypes: ['coily', 'curly'],
        description: '360 waves with a precision taper. The gold standard for coily hair.',
        isPremium: true,
        isTrending: true,
        barberScript: `"I want a taper fade — not too high, just up about 2 inches on the sides, blending from a 0 to a 1.5. Leave the top as-is, I'm working on my waves. Just trim the top with a 1.5 on a flat setting to keep it uniform. And please edge up my hairline sharp."`,
        guardNumbers: { sides: '0 to 1.5', top: '1.5 (flat)', hairline: 'straight razor edge' },
        stylingInstructions: 'Apply wave cream or pomade, brush in wave pattern, and sleep with a durag. Repeat daily.',
        maintenanceFrequency: 'Every 2–3 weeks',
    },
    {
        id: '9',
        name: 'Quiff with Skin Fade',
        slug: 'quiff-skin-fade',
        category: 'short',
        faceShapes: ['oval', 'oblong', 'heart'],
        hairTypes: ['straight', 'wavy'],
        description: 'Volume at the front, clean fade on the sides. Rock\'n\'roll meets barbershop.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I'd like a quiff with a skin fade. Skin on the sides at the bottom, blending up to a 3. Leave 3 to 3.5 inches on top and use scissors — I want volume at the front. Please keep length at the front to style it upward and slightly back."`,
        guardNumbers: { sides_bottom: '0', sides_blend: '3', top: 'Scissor, 3–3.5 inches' },
        stylingInstructions: 'Apply volumizing mousse to damp hair at the roots. Blow-dry lifting the fringe upward as you go. Finish with a light wax.',
        maintenanceFrequency: 'Every 3–4 weeks',
    },
    {
        id: '10',
        name: 'Edgar Cut',
        slug: 'edgar-cut',
        category: 'short',
        faceShapes: ['oval', 'square', 'diamond'],
        hairTypes: ['straight', 'wavy', 'curly'],
        description: 'Viral bowl-meets-fade hybrid. Bold, modern, street-style statement.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want an Edgar cut. High fade on the sides — skin to about mid-head — and a flat, blunt fringe cut straight across at the forehead. Keep about an inch of length on top, all even. Line the hairline very clean."`,
        guardNumbers: { sides: '0 to high fade', top: '1 inch uniform', fringe: 'Blunt scissor line' },
        maintenanceFrequency: 'Every 2–3 weeks',
    },

    // ── MEDIUM STYLES ─────────────────────────────────────────────────────────

    {
        id: '11',
        name: 'Flow / Curtain Parted',
        slug: 'flow-curtain-parted',
        category: 'medium',
        faceShapes: ['oval', 'square', 'oblong', 'heart'],
        hairTypes: ['straight', 'wavy'],
        description: 'Athletic, effortless flow parted in the middle. Works with or without texture.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want to grow out a flow look — curtains with a middle part. Just clean up the ends and shape the sides so it falls nicely. Don't take much length. I want it to sit about chin length eventually. Trim any split ends. No fade, just a natural taper on the sides."`,
        guardNumbers: { sides: 'Natural taper (no clipper)', top: 'Scissor shape only' },
        stylingInstructions: 'Work a curl-enhancing cream or light oil through damp hair. Part down the middle with your fingers and let air-dry or diffuse.',
        maintenanceFrequency: 'Shape-up every 6–8 weeks',
    },
    {
        id: '12',
        name: 'Messy Textured Crop',
        slug: 'messy-textured-crop',
        category: 'medium',
        faceShapes: ['oval', 'round', 'heart'],
        hairTypes: ['wavy', 'curly'],
        description: 'Effortlessly styled, textured all over. The off-duty celebrity look.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want a messy textured look. Leave about 2.5 to 3 inches all over, using scissors. Thin it out with texturizing shears if it's heavy. I want it to look lived-in and textured, not overly styled. Light taper — no clipper fade — just clean around the ears."`,
        guardNumbers: { all_over: 'Scissor, 2.5–3 inches', ears: 'Scissor taper' },
        stylingInstructions: 'Scrunch in sea salt spray to damp hair. Diffuse or air dry. Finish with a small amount of hair putty worked through the ends.',
        maintenanceFrequency: 'Every 5–6 weeks',
    },
    {
        id: '13',
        name: 'Pompadour',
        slug: 'pompadour',
        category: 'medium',
        faceShapes: ['oval', 'oblong', 'square'],
        hairTypes: ['straight', 'wavy'],
        description: 'Volume king. The Elvis of haircuts, modernized with a tight fade.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I'd like a pompadour. High to mid fade on the sides — skin at bottom, blending to a 3. Leave 4 inches on top so I can blow-dry it back and up into a pompadour shape. I need the length to work with the volume. Use scissors on top."`,
        technicalName: 'Modern Pompadour with High Fade',
        guardNumbers: { sides: '0 to 3 blend', top: 'Scissor, 4 inches' },
        stylingInstructions: 'Apply volumizing mousse to damp hair. Blow-dry lifting the top back and upward using a round brush. Finish with medium-hold pomade or paste, combing back.',
        maintenanceFrequency: 'Every 3 weeks',
    },
    {
        id: '14',
        name: 'Side Part + Undercut',
        slug: 'side-part-undercut',
        category: 'medium',
        faceShapes: ['oval', 'square', 'oblong'],
        hairTypes: ['straight', 'wavy'],
        description: 'Business on the sides, bold on top. Clean undercut meeting a crisp side part.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I'd like an undercut with a side part. Buzz the sides with a 1 or 2, going as high as the temples. Leave 3 inches on top and keep the hard part on the left. I want to be able to comb it to the side with a clear contrast between top and sides."`,
        guardNumbers: { sides: '1–2', top: 'Scissor, 3 inches' },
        stylingInstructions: 'Apply pomade or wax, comb all the way to the right over the hard part. Use a fine comb for clean lines.',
        maintenanceFrequency: 'Every 3–4 weeks',
    },
    {
        id: '15',
        name: 'Textured Fringe + Low Fade',
        slug: 'textured-fringe-low-fade',
        category: 'medium',
        faceShapes: ['oblong', 'oval', 'square'],
        hairTypes: ['straight', 'wavy', 'curly'],
        description: 'Versatile modern cut — textured fringe with clean sides.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want a textured fringe. Low fade on the sides — starting about an inch up, skin at the bottom blending to a 2. Leave 2.5 to 3 inches on top, using scissors. I want the fringe to fall forward with texture, not plastered down. Please trim the ends only."`,
        guardNumbers: { sides: '0 to 2', top: 'Scissor, 2.5–3 inches' },
        maintenanceFrequency: 'Every 4 weeks',
    },

    // ── LONG STYLES ───────────────────────────────────────────────────────────

    {
        id: '16',
        name: 'Man Bun Shape-Up',
        slug: 'man-bun-shape-up',
        category: 'long',
        faceShapes: ['oval', 'square', 'oblong'],
        hairTypes: ['straight', 'wavy', 'curly'],
        description: 'Maintain length for the bun while keeping sides neat.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I'm growing a man bun. I just need a shape-up — clean the split ends off the length, tidy up around the sides and neckline, but keep the length on top. Maybe a low taper on the sides. Don't touch the top length."`,
        guardNumbers: { sides: 'Light taper (1.5–2)', top: 'Split end trim only' },
        maintenanceFrequency: 'Shape-up every 6–8 weeks',
    },
    {
        id: '17',
        name: 'Shoulder-Length + Layers',
        slug: 'shoulder-length-layers',
        category: 'long',
        faceShapes: ['oval', 'oblong', 'heart'],
        hairTypes: ['wavy', 'curly', 'coily'],
        description: 'Long layered cut that removes bulk and defines movement.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I want to keep the length at about shoulder level but need layers put in to remove bulk and add movement. Dry cut if possible. Don't change the silhouette, just add internal layers to lighten it up. No fringe."`,
        guardNumbers: { length: 'Shoulder length (scissor)', layers: 'Internal, through mid-section' },
        stylingInstructions: 'Apply curl cream or lightweight oil through damp hair. Diffuse on low heat or air dry for best wave/curl definition.',
        maintenanceFrequency: 'Every 8–10 weeks',
    },
    {
        id: '18',
        name: 'Long Curly ReShape',
        slug: 'long-curly-reshape',
        category: 'long',
        faceShapes: ['oval', 'round', 'heart'],
        hairTypes: ['curly', 'coily'],
        description: 'Shape the curls without disrupting the pattern.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I have curly hair and I want to keep the length but just need it reshaped — cut it dry, curl by curl or in small sections so you can see how the curls naturally fall. I want an even round shape, no hard parts or fades. Just a curl-aware trim."`,
        guardNumbers: { technique: 'Dry cut, curl-by-curl', length: 'Maintain, remove 0.5–1 inch' },
        stylingInstructions: 'Apply curl-defining cream to wet hair section by section. Scrunch upward and diffuse to activate curl pattern.',
        maintenanceFrequency: 'Every 8–12 weeks',
    },

    // ── BEARD STYLES ──────────────────────────────────────────────────────────

    {
        id: '19',
        name: 'Short Stubble Edge-Up',
        slug: 'short-stubble-edge-up',
        category: 'beard',
        faceShapes: ['oval', 'square', 'round', 'oblong', 'heart', 'diamond'],
        hairTypes: ['straight', 'wavy', 'curly', 'coily'],
        description: 'The 5 o\'clock shadow, perfected. Clean lines that frame the face.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want to keep a short stubble look, about a 2 or 3 on the beard guard. The most important part is the line-up — please edge the cheek line and the neckline really cleanly with a razor. I want the border of the beard to look very defined."`,
        guardNumbers: { beard_length: '2–3', cheek_line: 'Razor edge', neck_line: 'Razor edge, one finger above Adam\'s apple' },
        maintenanceFrequency: 'Touch up every 1–2 weeks',
    },
    {
        id: '20',
        name: 'Medium Beard Fade',
        slug: 'medium-beard-fade',
        category: 'beard',
        faceShapes: ['oval', 'round', 'square'],
        hairTypes: ['straight', 'wavy', 'curly', 'coily'],
        description: 'Full beard that fades into the skin at the cheeks. Masculine and refined.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want a medium beard — keep it about half an inch to an inch long on the chin and jaw. But I want the cheeks faded — shorter as you go up toward the cheekbone, blending into skin. Clean up the neckline under the jaw with a razor. Line the top of the beard on the cheeks in a natural arc."`,
        guardNumbers: { chin_jaw: '4–6', cheeks_fade: '1 to 2 going up', neckline: 'Razor clean' },
        stylingInstructions: 'Apply beard oil daily. Use a boar-bristle beard brush to train and shape.',
        maintenanceFrequency: 'Monthly trim + weekly line-up',
    },
    {
        id: '21',
        name: 'Goatee + Clean Shave Sides',
        slug: 'goatee-clean-shave',
        category: 'beard',
        faceShapes: ['round', 'oblong', 'oval'],
        hairTypes: ['straight', 'wavy', 'curly', 'coily'],
        description: 'Goatee that elongates round faces. Sides fully clean-shaved.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I want a goatee — mustache connected to a chin patch. Clean shave everything else — cheeks and sides completely smooth. Keep the goatee about half an inch and line it up precisely. Mustache connected over the top lip."`,
        guardNumbers: { goatee: '4 (0.5 inch)', sides_cheeks: 'Clean razor shave' },
        maintenanceFrequency: 'Every 2–3 weeks',
    },
    {
        id: '22',
        name: 'Full Beard Trim + Shape',
        slug: 'full-beard-trim-shape',
        category: 'beard',
        faceShapes: ['oval', 'square', 'oblong', 'diamond'],
        hairTypes: ['straight', 'wavy', 'curly', 'coily'],
        description: 'Full beard maintained at peak condition. Even length, defined lines.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I want to maintain my full beard. Keep as much length as possible but even it out — trim any scraggly hairs, shape the cheek lines into a natural arc, clean up the neckline with a razor about one finger above the Adam's apple. I want the mustache trimmed to just above the lip."`,
        guardNumbers: { overall: '6–8 (or scissor)', cheek_line: 'Natural arc', neckline: 'One finger above Adam\'s apple' },
        stylingInstructions: 'Use beard balm for hold and shape. Apply beard oil daily for softness. Comb through morning and night.',
        maintenanceFrequency: 'Every 4–6 weeks',
    },

    // ── COMBO STYLES ──────────────────────────────────────────────────────────

    {
        id: '23',
        name: 'Skin Fade + Full Beard',
        slug: 'skin-fade-full-beard',
        category: 'combo',
        faceShapes: ['oval', 'square', 'oblong', 'diamond'],
        hairTypes: ['straight', 'wavy', 'curly', 'coily'],
        description: 'The classic contrast. Short shaved sides meeting a full, thick beard.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want a skin fade that actually connects into my beard — starting from skin at the bottom of the sides and back, blending up to a 2 or 3, with the beard connecting seamlessly below. On top I want 2.5 to 3 inches, scissors. The beard should be trimmed to about 1 to 1.5 inches."`,
        technicalName: 'Skin Fade with Seamless Beard Blend',
        guardNumbers: { sides: '0 to 3', top: 'Scissor, 2.5–3 inches', beard: '6–8 (1–1.5 inch)' },
        stylingInstructions: 'Style hair with pomade. Condition beard daily, trim with scissors to keep it neat.',
        maintenanceFrequency: 'Every 3–4 weeks',
    },
    {
        id: '24',
        name: 'Textured Top + Stubble',
        slug: 'textured-top-stubble',
        category: 'combo',
        faceShapes: ['oval', 'square', 'round'],
        hairTypes: ['straight', 'wavy'],
        description: 'Rugged and modern. Textured crop with perfectly shaped stubble.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want a mid fade with a textured top — about 2 inches on top, scissors only, a little choppy for texture. On the beard side, I want stubble — keep it at a 2 or 3 guard, all over even, then just clean up the cheek line and neck line with a razor."`,
        guardNumbers: { sides: '0 to 2 blend', top: 'Scissor, 2 inches (choppy)', beard: '2–3 guard, razor edges' },
        maintenanceFrequency: 'Every 3 weeks',
    },
    {
        id: '25',
        name: 'Bald Fade + Beard',
        slug: 'bald-fade-beard',
        category: 'combo',
        faceShapes: ['oval', 'diamond', 'square'],
        hairTypes: ['coily', 'curly'],
        description: 'Zero on top fading into a full beard. The power move for thinning hair.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I want to go bald on top with a skin fade — go all the way down to skin on the top and sides. The key is blending it perfectly into the beard below so it all connects. The beard should be about an inch long. Fade it up from the beard into the bald area seamlessly."`,
        guardNumbers: { top: '0 (bald)', sides: '0 to beard blend', beard: '8 (1 inch)' },
        maintenanceFrequency: 'Every 2–3 weeks',
    },

    // ── ADDITIONAL POPULAR STYLES ─────────────────────────────────────────────

    {
        id: '26',
        name: 'Taper + Natural Curls',
        slug: 'taper-natural-curls',
        category: 'short',
        faceShapes: ['oval', 'round', 'square'],
        hairTypes: ['curly', 'coily'],
        description: 'Let curls breathe on top with a clean, low taper on the sides.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I have natural curls and I want to keep them. Just give me a low taper on the sides — a 2 or 3 tapering down to a 1. Leave the top as long as possible and just shape it so it looks round and even. Stretch the curl a little if you need to see the length."`,
        guardNumbers: { sides: '1 to 3 taper', top: 'Scissor shape only (keep length)' },
        maintenanceFrequency: 'Every 4–5 weeks',
    },
    {
        id: '27',
        name: 'Drop Fade + Two-Step',
        slug: 'drop-fade-two-step',
        category: 'short',
        faceShapes: ['oval', 'round', 'square', 'diamond'],
        hairTypes: ['coily', 'curly'],
        description: 'Dramatic drop fade creating two distinct length levels. Maximum shape.',
        isPremium: true,
        isTrending: true,
        barberScript: `"I want a drop fade — where the fade drops down behind the ear and curves around the back of the head. I also want a two-step, meaning a clear visual step from the top section down to the faded sides. Leave about 1.5 to 2 inches on top evenly. Use a 1.5 with a curved drop."`,
        technicalName: 'Drop Fade with Two-Step',
        guardNumbers: { top: '1.5–2 (clipper flat)', fade_line: 'Curved drop, skin below' },
        maintenanceFrequency: 'Every 2–3 weeks',
    },
    {
        id: '28',
        name: 'Zero Fade + Design',
        slug: 'zero-fade-design',
        category: 'short',
        faceShapes: ['oval', 'square', 'diamond'],
        hairTypes: ['coily', 'curly', 'wavy'],
        description: 'Clean zero fade with a razor art design on the side.',
        isPremium: true,
        isTrending: true,
        barberScript: `"I want a zero fade on the sides — going down to skin — with a simple design on the left side. I'm thinking [describe design: line, lightning bolt, fade pattern]. Leave the top at about a 1.5 for a short, defined look. Line the hairline sharp."`,
        guardNumbers: { sides: '0 (zero fade)', top: '1.5', design: 'Razor art (customer specified)' },
        maintenanceFrequency: 'Every 2 weeks to maintain design',
    },
    {
        id: '29',
        name: 'Afro + Shape-Up',
        slug: 'afro-shape-up',
        category: 'short',
        faceShapes: ['oval', 'oblong', 'heart'],
        hairTypes: ['coily'],
        description: 'Natural full afro with a crisp, sharp shape-up around the hairline.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I want to keep my natural afro but clean up the shape. Just pick it out and shape it into an even round. Then do a really clean shape-up — sharp hairline on the front, corners, and around the ears. Don't cut any length, just shape and edge me up."`,
        guardNumbers: { technique: 'Afro pick + shape', edges: 'Razor or T-blade edge-up' },
        maintenanceFrequency: 'Shape-up every 2–3 weeks',
    },
    {
        id: '30',
        name: 'Low Taper + Waves',
        slug: 'low-taper-waves',
        category: 'short',
        faceShapes: ['oval', 'round', 'square'],
        hairTypes: ['coily', 'wavy'],
        description: 'Perfect foundation for 360 waves with a clean low taper.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I'm maintaining my waves. I just need a low taper — a 1.5 at the bottom fading up to a 2 or 3. Keep the top at a 1.5 all over. Edge up my hairline super clean. That's all I need."`,
        guardNumbers: { sides: '1.5 to 3', top: '1.5', hairline: 'T-blade or razor' },
        maintenanceFrequency: 'Every 2–3 weeks',
    },
    {
        id: '31',
        name: 'Mullet / Modern Shag',
        slug: 'modern-shag',
        category: 'medium',
        faceShapes: ['oval', 'square', 'heart'],
        hairTypes: ['wavy', 'straight'],
        description: 'Business in the front, party in the back — the ironic cool-kid cut.',
        isPremium: true,
        isTrending: true,
        barberScript: `"I want a modern shag or mullet. Short at the top and sides — about 2 inches — but keep it longer at the back, maybe 3 to 4 inches. Add layers throughout for texture. Light curtain fringe at the front. Low fade or no fade — just a natural taper on the sides."`,
        guardNumbers: { top_sides: 'Scissor, 2 inches', back: 'Scissor, 3–4 inches' },
        stylingInstructions: 'Apply sea salt spray to damp hair. Diffuse or air dry for natural texture.',
        maintenanceFrequency: 'Every 5–6 weeks',
    },
    {
        id: '32',
        name: 'Blowout High Top',
        slug: 'blowout-high-top',
        category: 'short',
        faceShapes: ['oblong', 'oval'],
        hairTypes: ['curly', 'coily'],
        description: 'Dramatic height on top with fully blurred sides. The height adds length to the face.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I want a blowout — the sides faded to skin, and the top blown out straight up. I need about 3 to 4 inches of length on top for the height. Keep the sides very clean skin fade. Don't touch the top length, I want maximum height when I blow it out."`,
        guardNumbers: { sides: '0 (skin)', top: 'Natural length, 3–4 inches keep' },
        stylingInstructions: 'Blow-dry while holding a brush pointing straight up from the roots. Apply a light holding spray to maintain lift.',
        maintenanceFrequency: 'Every 3 weeks for sides',
    },
    {
        id: '33',
        name: 'Space Buns / Top Knot',
        slug: 'top-knot',
        category: 'medium',
        faceShapes: ['oval', 'oblong', 'round'],
        hairTypes: ['straight', 'wavy', 'curly'],
        description: 'All-back top knot with clean, low-fade sides.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I want a top knot look. Low to mid fade on the sides so it looks clean when my hair is up. Leave 4 to 5 inches on top so I can tie it back. Just a taper on the sides, no skin fade needed. Keep the neckline natural."`,
        guardNumbers: { sides: '2 to 3', top: 'Scissor, 4–5 inches' },
        maintenanceFrequency: 'Every 5–6 weeks',
    },
    {
        id: '34',
        name: 'Line-Up Only',
        slug: 'line-up-only',
        category: 'short',
        faceShapes: ['oval', 'round', 'square', 'oblong', 'diamond', 'heart'],
        hairTypes: ['straight', 'wavy', 'curly', 'coily'],
        description: 'For when you just need a clean edge-up without changing your cut.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I just need a line-up or edge-up today — no cut, just clean up my hairline. Sharp edges on the front, sides, and around my ears. Use the T-blade and razor for the finish. My neck too — keep it looking fresh."`,
        guardNumbers: { technique: 'T-blade + razor edge-up only', hairline: 'Front + sides + nape' },
        maintenanceFrequency: 'Every 1–2 weeks',
    },
    {
        id: '35',
        name: 'Temple Fade + Comb Over',
        slug: 'temple-fade-comb-over',
        category: 'short',
        faceShapes: ['oval', 'round', 'square'],
        hairTypes: ['straight', 'wavy'],
        description: 'Subtle temple fade with a clean comb-over. Office-ready.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I want a temple fade — just fading out at the temples cleanly, about 2 inches up. Leave 2 inches on top and comb it to the side. I don't want a full fade, just the temples cleaned up. No hard part, just a natural comb-over."`,
        guardNumbers: { temples: '0 to 2 (2 inch height)', top: 'Scissor, 2 inches' },
        maintenanceFrequency: 'Every 4 weeks',
    },

    // ── ADDITIONAL PREMIUM & TRENDING ─────────────────────────────────────────

    {
        id: '36',
        name: 'Ivy League / Princeton',
        slug: 'ivy-league',
        category: 'short',
        faceShapes: ['oval', 'square', 'oblong'],
        hairTypes: ['straight', 'wavy'],
        description: 'The clean, preppy look. Long enough on top to part, short on the sides.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I'd like an Ivy League or Princeton cut. Low taper on the sides — a 2 tapering to a 1. Leave 2 inches on top so I can comb it neatly to the side. Clean, classic look. Square up the neckline."`,
        guardNumbers: { sides: '1 to 2 taper', top: 'Scissor, 2 inches' },
        maintenanceFrequency: 'Every 4–5 weeks',
    },
    {
        id: '37',
        name: 'Mohawk Fade',
        slug: 'mohawk-fade',
        category: 'short',
        faceShapes: ['oblong', 'oval', 'diamond'],
        hairTypes: ['straight', 'wavy', 'coily'],
        description: 'Faded sides rising dramatically to a strip of length on top.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I want a mohawk fade. Skin fade on both sides going up high — almost to the very top of the head. Leave a strip of hair in the center, about 2 to 2.5 inches of length. The center strip should be about 2 inches wide. Edge up the front of the center strip clean."`,
        guardNumbers: { sides: '0 (skin, high)', center_strip: 'Scissor, 2–2.5 inches, 2 inch width' },
        maintenanceFrequency: 'Every 2–3 weeks',
    },
    {
        id: '38',
        name: 'Disconnected Undercut',
        slug: 'disconnected-undercut',
        category: 'medium',
        faceShapes: ['oval', 'square', 'oblong'],
        hairTypes: ['straight', 'wavy'],
        description: 'Dramatic length contrast — shaved sides with thick, long top.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I want a disconnected undercut. Skin or zero on the sides — very clean and high — with no blending into the top. The top stays at 4 or 5 inches. There should be a sharp visual disconnect between the top and sides. No fade, just a hard line."`,
        guardNumbers: { sides: '0 (no blend)', top: 'Scissor, 4–5 inches' },
        stylingInstructions: 'Slick top section to one side using strong hold pomade and a fine comb. The contrast with bare sides is the whole look.',
        maintenanceFrequency: 'Every 3–4 weeks for sides',
    },
    {
        id: '39',
        name: 'Loc Fade',
        slug: 'loc-fade',
        category: 'short',
        faceShapes: ['oval', 'round', 'square'],
        hairTypes: ['coily'],
        description: 'For those with starter or mature locs — clean fade underneath.',
        isPremium: true,
        isTrending: true,
        barberScript: `"I have locs and I just want the sides faded to clean it up. Mid to low fade, skin at the bottom, blending up to about 2. Don't touch the locs on top. Just clean up the sides and the neckline, and retwist the edges if you can."`,
        guardNumbers: { sides: '0 to 2', locs: 'Untouched' },
        maintenanceFrequency: 'Loc maintenance monthly, fade every 3–4 weeks',
    },
    {
        id: '40',
        name: 'Flow Back + Low Fade',
        slug: 'flow-back-low-fade',
        category: 'medium',
        faceShapes: ['oval', 'oblong', 'square'],
        hairTypes: ['wavy', 'straight'],
        description: 'Hair swept completely back from the face with a clean fade on sides.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I want all my hair pushed back — no part, no fringe, everything slicked back from the forehead. I need about 3 to 4 inches on top to do this properly. Low fade on the sides, skin at the bottom blending to a 2. Use scissors on top, trim the length a little but keep the shape."`,
        guardNumbers: { sides: '0 to 2', top: 'Scissor, 3–4 inches' },
        stylingInstructions: 'Apply pomade to damp hair. Use a brush to force all hair backward from the forehead. Let dry with structure.',
        maintenanceFrequency: 'Every 4–5 weeks',
    },
    {
        id: '41',
        name: 'Box Fade',
        slug: 'box-fade',
        category: 'short',
        faceShapes: ['round', 'oval', 'square'],
        hairTypes: ['coily'],
        description: 'Natural shaped afro box at the top with a high flush fade.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want a box fade — the top should be shaped into a square box shape, picked out, and the sides should high fade to skin. The top should have a flat surface when looked at from the front and a square silhouette. Let's say 2 to 3 inches on top."`,
        technicalName: 'High Skin Fade with Square Box Top',
        guardNumbers: { sides: '0 (skin, high)', top: '2–3 inches natural coily, shaped square' },
        maintenanceFrequency: 'Every 3–4 weeks',
    },
    {
        id: '42',
        name: 'Caesar Cut',
        slug: 'caesar-cut',
        category: 'short',
        faceShapes: ['oval', 'round', 'oblong', 'heart'],
        hairTypes: ['straight', 'wavy', 'curly'],
        description: 'Roman emperor energy. Horizontal fringe, short uniform length.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I want a Caesar cut. All one length — about 1.5 to 2 inches on top — with a horizontal, slightly textured fringe at the front. Low taper on the sides blending into the top. Everything even. No fades, just a gradual taper."`,
        guardNumbers: { all_over: 'Scissor, 1.5–2 inches', sides: 'Light taper' },
        maintenanceFrequency: 'Every 3–4 weeks',
    },
    {
        id: '43',
        name: 'Skin Fade + Spiky Top',
        slug: 'skin-fade-spiky-top',
        category: 'short',
        faceShapes: ['oval', 'square', 'diamond'],
        hairTypes: ['straight', 'wavy'],
        description: 'Clean faded sides with a spiky, gel-styled top. The 2000s classic, modernized.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I want a mid to high skin fade on the sides, and I need about 2 to 2.5 inches on top so I can spike it up. Use scissors on top, keep it long enough to stand up with some product. Please also line up my hairline clean."`,
        guardNumbers: { sides: '0 skin, mid-high', top: 'Scissor, 2–2.5 inches' },
        stylingInstructions: 'Apply strong-hold gel or wax to damp hair. Use your fingers to push hair upward into spikes and hold in place. Let dry.',
        maintenanceFrequency: 'Every 3–4 weeks',
    },
    {
        id: '44',
        name: 'Shoulder-Length Flow + Taper',
        slug: 'shoulder-length-taper',
        category: 'long',
        faceShapes: ['oval', 'square', 'oblong'],
        hairTypes: ['straight', 'wavy'],
        description: 'Clean, athletic flow to the shoulders with tapered sides to keep it sharp.',
        isPremium: true,
        isTrending: true,
        barberScript: `"I want to grow a flow look. Just a light taper on the sides — a 3, not a fade — and trim the ends of the length so it's even just below the ear or at shoulder level. Keep the weight in the back, and don't cut any length off the top. Natural part."`,
        guardNumbers: { sides: '3 (natural taper)', ends: 'Scissor shape, shoulder level' },
        maintenanceFrequency: 'Every 6–8 weeks',
    },
    {
        id: '45',
        name: 'Twists + Fade',
        slug: 'twists-fade',
        category: 'short',
        faceShapes: ['oval', 'round', 'square'],
        hairTypes: ['coily', 'curly'],
        description: 'Two-strand twists or Bantu knots with a clean skin or low fade underneath.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I have twists and I just want the sides faded clean. Low to mid fade, skin at the bottom, going up about 2 to 3 inches, blending to a 2. Don't touch the twists on top. Just clean the perimeter and fade the sides."`,
        guardNumbers: { sides: '0 to 2, 2–3 inch height', top: 'Untouched' },
        maintenanceFrequency: 'Fade every 3–4 weeks, twists as needed',
    },
    {
        id: '46',
        name: 'Crop + Brow Length Fringe',
        slug: 'crop-brow-fringe',
        category: 'short',
        faceShapes: ['oblong', 'oval', 'heart'],
        hairTypes: ['straight', 'wavy', 'curly'],
        description: 'Soft crop with a fringe that hits right at the brow — covers forehead effectively.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want a crop with the fringe cut at eyebrow level. Mid fade on the sides — skin at bottom, blend up to a 2. Leave about 1.5 inches on top all over, and cut the fringe straight across right at my eyebrows. It can be slightly textured, not perfectly straight."`,
        guardNumbers: { sides: '0 to 2 blend', top: '1.5 inches', fringe: 'Brow-level scissor' },
        maintenanceFrequency: 'Every 3–4 weeks',
    },
    {
        id: '47',
        name: 'Braided / Cornrow Shape-Up',
        slug: 'cornrow-shape-up',
        category: 'short',
        faceShapes: ['oval', 'round', 'square', 'oblong'],
        hairTypes: ['coily'],
        description: 'Fresh edges to complement cornrow or braid styles.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I have cornrows and I just need a fresh edge-up. My hairline in the front, the sides, and around the ears. Use the T-blade and razor for a super clean finish. Don't disturb the braids at all, just work around them."`,
        guardNumbers: { edges: 'Razor and T-blade edge-up', braids: 'Untouched' },
        maintenanceFrequency: 'Edge-up every 1–2 weeks',
    },
    {
        id: '48',
        name: 'Skin Fade + Dreads Maintenance',
        slug: 'dread-fade',
        category: 'medium',
        faceShapes: ['oval', 'round', 'square', 'diamond'],
        hairTypes: ['coily'],
        description: 'Maintain mature dreads with a sharp, clean skin fade underneath.',
        isPremium: true,
        isTrending: false,
        barberScript: `"I have dreads and I want the sides cleaned up with a skin fade. Start with skin at the bottom and blend up to a 2 where the dreads start. Keep the dreads untouched. Just clean up the sides and the nape of the neck. If you can palm-roll or retwist the roots that'd be great."`,
        guardNumbers: { sides: '0 to 2', dreads: 'Untouched (option to retwist roots)' },
        maintenanceFrequency: 'Every 4–6 weeks for fade',
    },
    {
        id: '49',
        name: 'Short Crop + Curtains',
        slug: 'short-crop-curtains',
        category: 'short',
        faceShapes: ['oval', 'round', 'heart', 'oblong'],
        hairTypes: ['straight', 'wavy'],
        description: 'Short sides and a soft curtain fringe parted in the center.',
        isPremium: false,
        isTrending: true,
        barberScript: `"I want short curtains — a middle part at the front with the fringe falling to each side, about eyebrow to cheekbone length. Low to mid fade on the sides. Leave enough on top for the curtain shape. Trim the ends to keep the shape."`,
        guardNumbers: { sides: '1 to 2 blend', top: 'Scissor, 2–3 inches + curtain fringe' },
        maintenanceFrequency: 'Every 4–5 weeks',
    },
    {
        id: '50',
        name: 'Classic High-and-Tight',
        slug: 'classic-high-and-tight',
        category: 'short',
        faceShapes: ['oval', 'square', 'oblong'],
        hairTypes: ['straight', 'wavy', 'curly'],
        description: 'Military-grade. Short on top, bare on sides. Authority and discipline.',
        isPremium: false,
        isTrending: false,
        barberScript: `"I want a high-and-tight. Zero on the sides going very high — almost to the top — and then leave about 0.5 to 1 inch on top. Keep the top flat and even. Square up the hairline. Neckline blocked straight."`,
        guardNumbers: { sides: '0 (very high)', top: '0.5–1 (flat top)' },
        maintenanceFrequency: 'Every 2–3 weeks',
    },
]

// Filter utility (mirrors the service-side logic for offline/local use)
export function filterHairstyles(
    styles: Hairstyle[],
    filters: {
        query?: string
        category?: string
        faceShape?: string
        isPremiumUser?: boolean
    }
): Hairstyle[] {
    let filtered = [...styles]

    if (filters.query && filters.query.trim()) {
        const q = filters.query.toLowerCase()
        filtered = filtered.filter(
            (s) =>
                s.name.toLowerCase().includes(q) ||
                s.description?.toLowerCase().includes(q) ||
                s.technicalName?.toLowerCase().includes(q)
        )
    }

    if (filters.category && filters.category !== 'all') {
        if (filters.category === 'trending') {
            filtered = filtered.filter((s) => s.isTrending)
        } else {
            filtered = filtered.filter((s) => s.category === filters.category)
        }
    }

    if (filters.faceShape) {
        filtered = filtered.sort((a, b) => {
            const aMatch = a.faceShapes.includes(filters.faceShape as FaceShape) ? -1 : 1
            const bMatch = b.faceShapes.includes(filters.faceShape as FaceShape) ? -1 : 1
            return aMatch - bMatch
        })
    } else {
        // Trending first for everyone
        filtered = filtered.sort((a, b) => (b.isTrending ? 1 : 0) - (a.isTrending ? 1 : 0))
    }

    return filtered
}
