// This file is auto-generated by running:
//   npm run gen:types
//
// Do not edit manually. Re-run after every database schema change.
//
// Command:
//   npx supabase gen types typescript --project-id nthiyvnjypvscgfeotyh --schema public > types/supabase.ts

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: {
                    id: string
                    username: string | null
                    full_name: string | null
                    avatar_url: string | null
                    date_of_birth: string | null
                    face_shape: string | null
                    skin_type: string | null
                    skin_tone: string | null
                    hair_type: string | null
                    hair_thickness: string | null
                    hair_concerns: string[] | null
                    has_beard: boolean
                    beard_style: string | null
                    grooming_goals: string[] | null
                    daily_time_available: string | null
                    budget_range: string | null
                    subscription_status: string
                    trial_started_at: string | null
                    trial_ends_at: string | null
                    subscription_expires_at: string | null
                    revenuecat_customer_id: string | null
                    total_xp: number
                    level: number
                    current_streak: number
                    longest_streak: number
                    last_checkin_date: string | null
                    onboarding_completed: boolean
                    onboarding_step: number
                    created_at: string
                    updated_at: string
                }
                Insert: Partial<Database['public']['Tables']['profiles']['Row']> & { id: string }
                Update: Partial<Database['public']['Tables']['profiles']['Row']>
            }
            routines: {
                Row: {
                    id: string
                    user_id: string
                    name: string
                    type: string | null
                    is_active: boolean
                    is_ai_generated: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: Partial<Database['public']['Tables']['routines']['Row']> & { user_id: string; name: string }
                Update: Partial<Database['public']['Tables']['routines']['Row']>
            }
            routine_steps: {
                Row: {
                    id: string
                    routine_id: string
                    step_order: number
                    title: string
                    description: string | null
                    category: string | null
                    product_name: string | null
                    product_affiliate_url: string | null
                    duration_seconds: number | null
                    is_premium_step: boolean
                    created_at: string
                }
                Insert: Partial<Database['public']['Tables']['routine_steps']['Row']> & { routine_id: string; step_order: number; title: string }
                Update: Partial<Database['public']['Tables']['routine_steps']['Row']>
            }
            habit_logs: {
                Row: {
                    id: string
                    user_id: string
                    routine_step_id: string
                    logged_date: string
                    completed: boolean
                    completed_at: string | null
                    note: string | null
                    created_at: string
                }
                Insert: Partial<Database['public']['Tables']['habit_logs']['Row']> & { user_id: string; routine_step_id: string; logged_date: string }
                Update: Partial<Database['public']['Tables']['habit_logs']['Row']>
            }
            streaks: {
                Row: {
                    id: string
                    user_id: string
                    current_streak: number
                    longest_streak: number
                    last_active_date: string | null
                    streak_started_at: string | null
                    total_days_completed: number
                    updated_at: string
                }
                Insert: Partial<Database['public']['Tables']['streaks']['Row']> & { user_id: string }
                Update: Partial<Database['public']['Tables']['streaks']['Row']>
            }
            badges: {
                Row: {
                    id: string
                    slug: string
                    name: string
                    description: string
                    icon_url: string | null
                    lottie_url: string | null
                    xp_reward: number
                    rarity: string
                    unlock_condition: Json | null
                    created_at: string
                }
                Insert: Partial<Database['public']['Tables']['badges']['Row']> & { slug: string; name: string; description: string }
                Update: Partial<Database['public']['Tables']['badges']['Row']>
            }
            user_badges: {
                Row: {
                    id: string
                    user_id: string
                    badge_id: string
                    earned_at: string
                    is_seen: boolean
                }
                Insert: Partial<Database['public']['Tables']['user_badges']['Row']> & { user_id: string; badge_id: string }
                Update: Partial<Database['public']['Tables']['user_badges']['Row']>
            }
            hairstyles: {
                Row: {
                    id: string
                    name: string
                    slug: string
                    category: string | null
                    face_shapes: string[] | null
                    hair_types: string[] | null
                    description: string | null
                    barber_script: string
                    technical_name: string | null
                    guard_numbers: Json | null
                    styling_instructions: string | null
                    maintenance_frequency: string | null
                    thumbnail_url: string | null
                    front_view_url: string | null
                    side_view_url: string | null
                    back_view_url: string | null
                    deepar_effect_id: string | null
                    is_premium: boolean
                    is_trending: boolean
                    view_count: number
                    created_at: string
                }
                Insert: Partial<Database['public']['Tables']['hairstyles']['Row']> & { name: string; slug: string; barber_script: string }
                Update: Partial<Database['public']['Tables']['hairstyles']['Row']>
            }
            saved_hairstyles: {
                Row: {
                    id: string
                    user_id: string
                    hairstyle_id: string
                    saved_at: string
                }
                Insert: Partial<Database['public']['Tables']['saved_hairstyles']['Row']> & { user_id: string; hairstyle_id: string }
                Update: Partial<Database['public']['Tables']['saved_hairstyles']['Row']>
            }
            skin_analysis_logs: {
                Row: {
                    id: string
                    user_id: string
                    photo_url: string | null
                    analysis_result: Json | null
                    detected_skin_type: string | null
                    detected_concerns: string[] | null
                    confidence_score: number | null
                    recommendations: string[] | null
                    analyzed_at: string
                }
                Insert: Partial<Database['public']['Tables']['skin_analysis_logs']['Row']> & { user_id: string }
                Update: Partial<Database['public']['Tables']['skin_analysis_logs']['Row']>
            }
            hair_loss_logs: {
                Row: {
                    id: string
                    user_id: string
                    photo_url: string
                    photo_angle: string | null
                    notes: string | null
                    logged_date: string
                    created_at: string
                }
                Insert: Partial<Database['public']['Tables']['hair_loss_logs']['Row']> & { user_id: string; photo_url: string }
                Update: Partial<Database['public']['Tables']['hair_loss_logs']['Row']>
            }
            product_scans: {
                Row: {
                    id: string
                    user_id: string
                    barcode: string
                    product_name: string | null
                    brand: string | null
                    category: string | null
                    ingredients: Json | null
                    safety_score: number | null
                    flagged_ingredients: string[] | null
                    recommendation: string | null
                    scanned_at: string
                }
                Insert: Partial<Database['public']['Tables']['product_scans']['Row']> & { user_id: string; barcode: string }
                Update: Partial<Database['public']['Tables']['product_scans']['Row']>
            }
            affiliate_clicks: {
                Row: {
                    id: string
                    user_id: string
                    product_id: string | null
                    product_name: string | null
                    affiliate_url: string | null
                    source: string | null
                    clicked_at: string
                }
                Insert: Partial<Database['public']['Tables']['affiliate_clicks']['Row']> & { user_id: string }
                Update: Partial<Database['public']['Tables']['affiliate_clicks']['Row']>
            }
            webhook_events: {
                Row: {
                    id: string
                    provider: string
                    event_id: string | null
                    event_type: string | null
                    payload: Json
                    received_at: string
                    processed_at: string | null
                    status: string
                    error_message: string | null
                }
                Insert: Partial<Database['public']['Tables']['webhook_events']['Row']> & { provider: string; payload: Json }
                Update: Partial<Database['public']['Tables']['webhook_events']['Row']>
            }
            notification_settings: {
                Row: {
                    id: string
                    user_id: string
                    morning_routine_enabled: boolean
                    morning_routine_time: string
                    night_routine_enabled: boolean
                    night_routine_time: string
                    streak_reminder_enabled: boolean
                    weekly_tips_enabled: boolean
                    badge_notifications_enabled: boolean
                    updated_at: string
                }
                Insert: Partial<Database['public']['Tables']['notification_settings']['Row']> & { user_id: string }
                Update: Partial<Database['public']['Tables']['notification_settings']['Row']>
            }
            ai_usage_logs: {
                Row: {
                    id: string
                    user_id: string
                    feature: string
                    used_date: string
                    meta: Json | null
                    created_at: string
                }
                Insert: Partial<Database['public']['Tables']['ai_usage_logs']['Row']> & { user_id: string; feature: string }
                Update: Partial<Database['public']['Tables']['ai_usage_logs']['Row']>
            }
        }
        Functions: {
            increment_xp: {
                Args: { user_id: string; amount: number }
                Returns: void
            }
            calculate_level: {
                Args: { xp: number }
                Returns: number
            }
        }
        Enums: Record<string, never>
    }
}
