// app/hairstyle-detail.tsx
// Phase 6 — Full hairstyle detail with barber script, guard numbers, save, share

import { useState, useRef } from 'react'
import {
    View,
    Text,
    StyleSheet,
    ScrollView,
    Pressable,
    Alert,
    Clipboard,
    Linking,
    Share,
    Image,
} from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { router, useLocalSearchParams } from 'expo-router'
import { Ionicons } from '@expo/vector-icons'
import Animated, { FadeInDown, FadeInUp } from 'react-native-reanimated'
import * as Haptics from 'expo-haptics'
import { LinearGradient } from 'expo-linear-gradient'
import { Colors } from '@/constants/colors'
import { Typography } from '@/constants/typography'
import { Spacing, BorderRadius } from '@/constants/spacing'
import { useSubscriptionStore } from '@/stores/subscription.store'
import { useUserStore } from '@/stores/user.store'
import { barberService } from '@/services/barber.service'
import { useSavedHairstyleIds, useSaveHairstyle, useUnsaveHairstyle } from '@/hooks/useBarber'
import { BarberCardModal } from '@/components/barber/BarberCardModal'
import { AnimatedScreen } from '@/components/ui/AnimatedScreen'
import { getHairstyleImage } from '@/constants/hairstyleImages'

// Face shape tips for beard/combo styles
const FACE_SHAPE_TIPS: Record<string, Record<string, string>> = {
    'short-stubble-edge-up': { round: 'Stubble adds definition to softer jawlines', square: 'Enhances your naturally strong jawline' },
    'medium-beard-fade': { round: 'The faded cheeks slim your face shape', oval: 'Works perfectly with your balanced proportions' },
    'goatee-clean-shave': { round: 'Goatees elongate round faces — great choice for your shape', oblong: 'Adds width at the chin for balance' },
    'full-beard-trim-shape': { oval: 'Your face shape can pull off any beard length', square: 'Softens angular features nicely' },
    'skin-fade-full-beard': { square: 'The contrast highlights your strong bone structure', oblong: 'The beard adds width — prevents looking too narrow' },
    'textured-top-stubble': { round: 'Textured top adds height while stubble defines the jaw', oval: 'A universally flattering combo for your face shape' },
    'bald-fade-beard': { oval: 'The shaved head + beard creates a striking, balanced look', diamond: 'Beard widens the lower face for perfect symmetry' },
}

export default function HairstyleDetailScreen() {
    const { slug } = useLocalSearchParams<{ slug: string }>()
    const hairstyle = barberService.getHairstyleBySlug(slug)
    const isPremium = useSubscriptionStore((s) => s.isPremium)
    const userId = useUserStore((s) => s.session?.user?.id)
    const profile = useUserStore((s) => s.profile)

    const { data: savedIds = [] } = useSavedHairstyleIds()
    const saveHairstyle = useSaveHairstyle()
    const unsaveHairstyle = useUnsaveHairstyle()
    const isSaved = savedIds.includes(hairstyle?.id ?? '')

    const [showCard, setShowCard] = useState(false)
    const [copyFeedback, setCopyFeedback] = useState(false)

    // Fire view count on mount
    if (hairstyle) barberService.incrementViewCount(slug)

    if (!hairstyle) {
        return (
            <SafeAreaView style={styles.container}>
                <Pressable style={styles.backBtn} onPress={() => router.back()}>
                    <Ionicons name="arrow-back" size={22} color={Colors.text.primary} />
                </Pressable>
                <View style={styles.centered}>
                    <Text style={styles.errorText}>Hairstyle not found.</Text>
                </View>
            </SafeAreaView>
        )
    }

    function toggleSave() {
        if (!userId) {
            Alert.alert('Sign In Required', 'Creating an account allows you to save your favorite styles and routines!')
            return
        }
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium)
        if (isSaved) {
            unsaveHairstyle.mutate(hairstyle!.id)
        } else {
            saveHairstyle.mutate(hairstyle!.id)
        }
    }

    function copyScript() {
        Clipboard.setString(hairstyle!.barberScript)
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)
        setCopyFeedback(true)
        setTimeout(() => setCopyFeedback(false), 2000)
    }

    async function shareViaWhatsApp() {
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)
        const msg = encodeURIComponent(
            `Hey! For my haircut I'd like:\n\n${hairstyle!.barberScript}\n\nGenerated by GroomAI`
        )
        const url = `whatsapp://send?text=${msg}`
        const supported = await Linking.canOpenURL(url)
        if (supported) {
            Linking.openURL(url)
        } else {
            // Fallback to system share
            Share.share({ message: hairstyle!.barberScript, title: hairstyle!.name })
        }
    }

    async function shareGeneric() {
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)
        Share.share({
            message: `${hairstyle!.name}\n\n${hairstyle!.barberScript}\n\n— Generated by GroomAI`,
            title: hairstyle!.name,
        })
    }

    return (
        <>
            <SafeAreaView style={styles.container} edges={['top']}>
                <AnimatedScreen>
                    {/* Header bar */}
                    <View style={styles.headerBar}>
                        <Pressable style={styles.backBtn} onPress={() => router.back()}>
                            <Ionicons name="arrow-back" size={22} color={Colors.text.primary} />
                        </Pressable>
                        <Pressable
                            style={[styles.saveBtn, isSaved && styles.saveBtnActive]}
                            onPress={toggleSave}
                        >
                            <Ionicons
                                name={isSaved ? 'heart' : 'heart-outline'}
                                size={22}
                                color={isSaved ? Colors.gold.primary : Colors.text.secondary}
                            />
                        </Pressable>
                    </View>

                    <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
                        {/* Photo area */}
                        <Animated.View entering={FadeInDown.duration(350)} style={styles.photoArea}>
                            {(() => {
                                const localImg = getHairstyleImage(hairstyle.slug)
                                return (
                                    <LinearGradient
                                        colors={['rgba(201,168,76,0.08)', 'transparent']}
                                        style={styles.photoGradient}
                                    >
                                        <View style={styles.photoGrid}>
                                            {[
                                                { label: 'Front', img: localImg?.front },
                                                { label: 'Side', img: localImg?.side },
                                                { label: 'Back', img: localImg?.back },
                                            ].map(({ label, img }) => (
                                                <View key={label} style={[styles.photoFrame, { overflow: 'hidden' }]}>
                                                    {img ? (
                                                        <Image source={img} style={{ width: '100%', height: '100%' }} resizeMode="cover" />
                                                    ) : (
                                                        <>
                                                            <Ionicons name="cut" size={24} color={Colors.gold.primary} />
                                                            <Text style={styles.photoLabel}>{label}</Text>
                                                        </>
                                                    )}
                                                </View>
                                            ))}
                                        </View>
                                    </LinearGradient>
                                )
                            })()}
                        </Animated.View>

                        {/* Style title + tags */}
                        <Animated.View entering={FadeInDown.delay(80).duration(350)} style={styles.titleSection}>
                            <Text style={styles.styleName}>{hairstyle.name}</Text>
                            {hairstyle.technicalName && (
                                <Text style={styles.technicalName}>{hairstyle.technicalName}</Text>
                            )}
                            <View style={styles.tagsRow}>
                                <View style={styles.tag}>
                                    <Text style={styles.tagText}>{hairstyle.category}</Text>
                                </View>
                                {hairstyle.isTrending && (
                                    <View style={[styles.tag, styles.tagGold]}>
                                        <Text style={[styles.tagText, { color: Colors.gold.primary }]}>🔥 Trending</Text>
                                    </View>
                                )}
                                {hairstyle.faceShapes.map((f) => (
                                    <View key={f} style={styles.tag}>
                                        <Text style={styles.tagText}>{f.charAt(0).toUpperCase() + f.slice(1)}</Text>
                                    </View>
                                ))}
                            </View>
                            {hairstyle.description && (
                                <Text style={styles.description}>{hairstyle.description}</Text>
                            )}

                            {/* Quick Action Row — Share */}
                            <View style={styles.quickActionRow}>
                                {/* AR Try-On — HIDDEN for v1 launch. DeepAR requires license + effect
                                 * files ($10-50 each) + native build. Uncomment when ready.
                                 * <Pressable
                                 *     style={styles.quickActionBtn}
                                 *     onPress={() => {
                                 *         Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)
                                 *         if (isPremium) {
                                 *             router.push('/ar-tryon' as any)
                                 *         } else {
                                 *             router.push('/paywall')
                                 *         }
                                 *     }}
                                 * >
                                 *     <Ionicons name="camera" size={16} color={Colors.gold.primary} />
                                 *     <Text style={styles.quickActionText}>Try it On</Text>
                                 *     {!isPremium && (
                                 *         <Ionicons name="lock-closed" size={10} color={Colors.gold.primary} />
                                 *     )}
                                 * </Pressable>
                                 */}
                                <Pressable style={styles.quickActionBtn} onPress={shareGeneric}>
                                    <Ionicons name="share-social" size={16} color={Colors.text.secondary} />
                                    <Text style={[styles.quickActionText, { color: Colors.text.secondary }]}>Share</Text>
                                </Pressable>
                            </View>
                        </Animated.View>

                        <View style={styles.divider} />

                        {/* ⭐ THE BARBER SCRIPT — the core value */}
                        <Animated.View entering={FadeInDown.delay(120).duration(350)} style={styles.section}>
                            <View style={styles.sectionHeader}>
                                <Ionicons name="chatbubble-ellipses" size={20} color={Colors.gold.primary} />
                                <Text style={styles.sectionTitle}>💬 What to say to your barber</Text>
                            </View>
                            <View style={styles.scriptCard}>
                                <Text style={styles.scriptText}>{hairstyle.barberScript}</Text>
                                <View style={styles.scriptActions}>
                                    <Pressable style={styles.scriptBtn} onPress={copyScript}>
                                        <Ionicons
                                            name={copyFeedback ? 'checkmark-circle' : 'copy-outline'}
                                            size={16}
                                            color={copyFeedback ? Colors.success : Colors.gold.primary}
                                        />
                                        <Text style={[styles.scriptBtnText, copyFeedback && { color: Colors.success }]}>
                                            {copyFeedback ? 'Copied!' : 'Copy Script'}
                                        </Text>
                                    </Pressable>
                                    <Pressable style={styles.scriptBtn} onPress={shareViaWhatsApp}>
                                        <Ionicons name="logo-whatsapp" size={16} color="#25D366" />
                                        <Text style={[styles.scriptBtnText, { color: '#25D366' }]}>WhatsApp</Text>
                                    </Pressable>
                                </View>
                            </View>
                        </Animated.View>

                        {/* Guard Numbers */}
                        {hairstyle.guardNumbers && Object.keys(hairstyle.guardNumbers).length > 0 && (
                            <Animated.View entering={FadeInDown.delay(150).duration(350)} style={styles.section}>
                                <Text style={styles.sectionTitle}>🔢 Guard Numbers</Text>
                                <View style={styles.guardCard}>
                                    {Object.entries(hairstyle.guardNumbers).map(([key, value]) => (
                                        <View key={key} style={styles.guardRow}>
                                            <Text style={styles.guardKey}>
                                                {key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}
                                            </Text>
                                            <Text style={styles.guardValue}>{value}</Text>
                                        </View>
                                    ))}
                                </View>
                            </Animated.View>
                        )}

                        {/* Styling Instructions */}
                        {hairstyle.stylingInstructions && (
                            <Animated.View entering={FadeInDown.delay(180).duration(350)} style={styles.section}>
                                <Text style={styles.sectionTitle}>💆 Styling</Text>
                                <View style={styles.infoBox}>
                                    <Text style={styles.infoText}>{hairstyle.stylingInstructions}</Text>
                                </View>
                            </Animated.View>
                        )}

                        {/* Maintenance */}
                        {hairstyle.maintenanceFrequency && (
                            <Animated.View entering={FadeInDown.delay(200).duration(350)} style={styles.section}>
                                <Text style={styles.sectionTitle}>🗓 Maintenance</Text>
                                <View style={styles.infoBox}>
                                    <Ionicons name="calendar-outline" size={16} color={Colors.gold.primary} style={{ marginRight: 6 }} />
                                    <Text style={styles.infoText}>{hairstyle.maintenanceFrequency}</Text>
                                </View>
                            </Animated.View>
                        )}

                        {/* Face Shape Tip (for beard/combo styles) */}
                        {(() => {
                            const faceShape = profile?.face_shape
                            const tips = FACE_SHAPE_TIPS[hairstyle.slug]
                            const tip = faceShape && tips ? tips[faceShape] : null
                            if (!tip) return null
                            return (
                                <Animated.View entering={FadeInDown.delay(210).duration(350)} style={styles.section}>
                                    <View style={styles.tipBox}>
                                        <Ionicons name="sparkles" size={18} color={Colors.gold.primary} />
                                        <Text style={styles.tipText}>{tip}</Text>
                                    </View>
                                </Animated.View>
                            )
                        })()}

                        <View style={styles.divider} />

                        {/* CTAs */}
                        <Animated.View entering={FadeInUp.delay(220).duration(350)} style={styles.ctaSection}>
                            {/* Primary: Generate Barber Card */}
                            <Pressable
                                style={styles.primaryCta}
                                onPress={() => {
                                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium)
                                    setShowCard(true)
                                }}
                            >
                                <LinearGradient
                                    colors={[Colors.gold.primary, Colors.gold.muted]}
                                    start={{ x: 0, y: 0 }}
                                    end={{ x: 1, y: 0 }}
                                    style={styles.primaryCtaGradient}
                                >
                                    <Ionicons name="card" size={20} color={Colors.bg.primary} />
                                    <Text style={styles.primaryCtaText}>Generate Barber Card</Text>
                                </LinearGradient>
                            </Pressable>

                            <View style={styles.secondaryCtaRow}>
                                {/* AR Try-On — v2 feature. Routes to Coming Soon placeholder.
                                 * Uncomment when DeepAR is integrated.
                                 * <Pressable
                                 *     style={styles.secondaryCta}
                                 *     onPress={() => {
                                 *         Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)
                                 *         if (isPremium) {
                                 *             router.push('/ar-tryon' as any)
                                 *         } else {
                                 *             router.push('/paywall')
                                 *         }
                                 *     }}
                                 * >
                                 *     <Ionicons name="camera" size={18} color={Colors.text.secondary} />
                                 *     <Text style={styles.secondaryCtaText}>Try it On</Text>
                                 *     {!isPremium && (
                                 *         <Ionicons name="lock-closed" size={12} color={Colors.gold.primary} />
                                 *     )}
                                 * </Pressable>
                                 */}

                                {/* Generic share */}
                                <Pressable style={styles.secondaryCta} onPress={shareGeneric}>
                                    <Ionicons name="share-social" size={18} color={Colors.text.secondary} />
                                    <Text style={styles.secondaryCtaText}>Share</Text>
                                </Pressable>
                            </View>
                        </Animated.View>
                    </ScrollView>
                </AnimatedScreen>
            </SafeAreaView>

            {/* Barber Card Modal */}
            {showCard && (
                <BarberCardModal
                    hairstyle={hairstyle}
                    onClose={() => setShowCard(false)}
                />
            )}
        </>
    )
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.bg.primary },
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    errorText: { ...Typography.body, color: Colors.text.secondary },
    scroll: { paddingBottom: 60 },

    headerBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: Spacing.lg,
        paddingVertical: Spacing.sm,
        zIndex: 10,
        elevation: 10,
    },
    backBtn: {
        width: 40, height: 40,
        borderRadius: 20,
        backgroundColor: Colors.bg.secondary,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: Colors.bg.tertiary,
    },
    saveBtn: {
        width: 40, height: 40,
        borderRadius: 20,
        backgroundColor: Colors.bg.secondary,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: Colors.bg.tertiary,
    },
    saveBtnActive: {
        borderColor: Colors.gold.muted,
        backgroundColor: Colors.overlay.gold,
    },

    photoArea: { marginHorizontal: Spacing.lg, marginBottom: Spacing.md },
    photoGradient: { borderRadius: BorderRadius.lg, overflow: 'hidden', padding: Spacing.sm },
    photoGrid: {
        flexDirection: 'row',
        gap: Spacing.sm,
        height: 160,
    },
    photoFrame: {
        flex: 1,
        backgroundColor: Colors.bg.secondary,
        borderRadius: BorderRadius.md,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: Colors.bg.tertiary,
        gap: Spacing.xs,
    },
    photoLabel: { ...Typography.caption, color: Colors.text.tertiary },

    titleSection: { paddingHorizontal: Spacing.lg, marginBottom: Spacing.md },
    styleName: { ...Typography.h1, color: Colors.text.primary, marginBottom: 4 },
    technicalName: { ...Typography.small, color: Colors.text.tertiary, marginBottom: Spacing.sm, fontStyle: 'italic' },
    tagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs, marginBottom: Spacing.sm },
    tag: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        backgroundColor: Colors.bg.secondary,
        borderRadius: BorderRadius.full,
        borderWidth: 1,
        borderColor: Colors.bg.tertiary,
    },
    tagGold: { borderColor: Colors.gold.muted },
    tagText: { ...Typography.caption, color: Colors.text.secondary, textTransform: 'capitalize' },
    description: { ...Typography.body, color: Colors.text.secondary, lineHeight: 22 },

    quickActionRow: {
        flexDirection: 'row',
        gap: Spacing.sm,
        marginTop: Spacing.md,
    },
    quickActionBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 8,
        paddingHorizontal: Spacing.md,
        borderRadius: BorderRadius.full,
        backgroundColor: Colors.bg.secondary,
        borderWidth: 1,
        borderColor: Colors.bg.tertiary,
    },
    quickActionText: { ...Typography.small, color: Colors.gold.primary, fontWeight: '600' },

    divider: { height: 1, backgroundColor: Colors.bg.tertiary, marginVertical: Spacing.md, marginHorizontal: Spacing.lg },

    section: { paddingHorizontal: Spacing.lg, marginBottom: Spacing.md },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginBottom: Spacing.sm },
    sectionTitle: { ...Typography.h3, color: Colors.text.primary, marginBottom: Spacing.sm },

    // Barber Script card
    scriptCard: {
        backgroundColor: Colors.bg.secondary,
        borderRadius: BorderRadius.lg,
        padding: Spacing.md,
        borderWidth: 1,
        borderColor: Colors.gold.muted,
        borderLeftWidth: 3,
        borderLeftColor: Colors.gold.primary,
    },
    scriptText: { ...Typography.body, color: Colors.text.primary, lineHeight: 24, fontStyle: 'italic' },
    scriptActions: {
        flexDirection: 'row',
        gap: Spacing.sm,
        marginTop: Spacing.md,
        paddingTop: Spacing.sm,
        borderTopWidth: 1,
        borderTopColor: Colors.bg.tertiary,
    },
    scriptBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingVertical: 6,
        paddingHorizontal: Spacing.sm,
        borderRadius: BorderRadius.sm,
        backgroundColor: Colors.bg.tertiary,
    },
    scriptBtnText: { ...Typography.small, color: Colors.gold.primary, fontWeight: '600' },

    // Guard numbers
    guardCard: {
        backgroundColor: Colors.bg.secondary,
        borderRadius: BorderRadius.lg,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: Colors.bg.tertiary,
    },
    guardRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: Colors.bg.tertiary,
    },
    guardKey: { ...Typography.body, color: Colors.text.secondary, flex: 1 },
    guardValue: { ...Typography.bodyMedium, color: Colors.text.primary, fontWeight: '700', textAlign: 'right' },

    // Info boxes (styling, maintenance)
    infoBox: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: Colors.bg.secondary,
        borderRadius: BorderRadius.md,
        padding: Spacing.md,
        borderWidth: 1,
        borderColor: Colors.bg.tertiary,
    },
    infoText: { ...Typography.body, color: Colors.text.secondary, lineHeight: 22, flex: 1 },

    // CTAs
    ctaSection: { paddingHorizontal: Spacing.lg, paddingBottom: Spacing.xl, gap: Spacing.sm },
    primaryCta: { borderRadius: BorderRadius.lg, overflow: 'hidden' },
    primaryCtaGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: Spacing.sm,
        paddingVertical: 16,
    },
    primaryCtaText: { ...Typography.h3, color: Colors.bg.primary, fontWeight: '800' },
    secondaryCtaRow: { flexDirection: 'row', gap: Spacing.sm },
    secondaryCta: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: Spacing.xs,
        paddingVertical: 12,
        borderRadius: BorderRadius.md,
        borderWidth: 1,
        borderColor: Colors.bg.tertiary,
        backgroundColor: Colors.bg.secondary,
    },
    secondaryCtaText: { ...Typography.bodyMedium, color: Colors.text.secondary },

    // Hero image (for styles with local images)
    heroImageWrapper: {
        width: '100%',
        height: 280,
        borderRadius: BorderRadius.lg,
        overflow: 'hidden',
        backgroundColor: Colors.bg.secondary,
    },
    heroImage: {
        width: '100%',
        height: '100%',
    },

    // Face shape tip box
    tipBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Spacing.sm,
        backgroundColor: Colors.overlay.gold,
        borderRadius: BorderRadius.md,
        padding: Spacing.md,
        borderWidth: 1,
        borderColor: Colors.gold.muted,
    },
    tipText: {
        ...Typography.body,
        color: Colors.gold.primary,
        flex: 1,
        fontWeight: '600',
    },
})
